name: discourse
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^3.1.3
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  firebase_database: ^4.3.0
  permission_handler: ^3.0.0
  provider: ^4.3.2+2
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true